// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackFocus.Infraestructure.Data;

#nullable disable

namespace TrackFocus.Infraestructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227164142_EstabelecendoRelacionamentos")]
    partial class EstabelecendoRelacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DetalheMusculacaoExercicio", b =>
                {
                    b.Property<int>("DetalhesId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciciosId")
                        .HasColumnType("int");

                    b.HasKey("DetalhesId", "ExerciciosId");

                    b.HasIndex("ExerciciosId");

                    b.ToTable("DetalheMusculacaoExercicio");
                });

            modelBuilder.Entity("ExercicioTreino", b =>
                {
                    b.Property<int>("ExerciciosId")
                        .HasColumnType("int");

                    b.Property<int>("TreinosId")
                        .HasColumnType("int");

                    b.HasKey("ExerciciosId", "TreinosId");

                    b.HasIndex("TreinosId");

                    b.ToTable("ExercicioTreino");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nm_categoria");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.DetalheMusculacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NumRepeticoes")
                        .HasColumnType("int")
                        .HasColumnName("qt_repeticoes");

                    b.Property<int?>("NumSeries")
                        .HasColumnType("int")
                        .HasColumnName("qt_series");

                    b.Property<int?>("SerieId")
                        .HasColumnType("int")
                        .HasColumnName("cd_serieId");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("DetalheMusculacao");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("cd_categoriaId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nm_exercicio");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Exercicio");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Peso")
                        .HasColumnType("int")
                        .HasColumnName("qt_peso");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int")
                        .HasColumnName("qt_repeticoes");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("cd_userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Treino");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DetalheMusculacaoExercicio", b =>
                {
                    b.HasOne("TrackFocus.Domain.Entities.DetalheMusculacao", null)
                        .WithMany()
                        .HasForeignKey("DetalhesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackFocus.Domain.Entities.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExerciciosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExercicioTreino", b =>
                {
                    b.HasOne("TrackFocus.Domain.Entities.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExerciciosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackFocus.Domain.Entities.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.DetalheMusculacao", b =>
                {
                    b.HasOne("TrackFocus.Domain.Entities.Serie", "Serie")
                        .WithMany("Detalhes")
                        .HasForeignKey("SerieId");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Exercicio", b =>
                {
                    b.HasOne("TrackFocus.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Exercicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Treino", b =>
                {
                    b.HasOne("TrackFocus.Domain.Entities.User", "User")
                        .WithMany("Treinos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.Serie", b =>
                {
                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("TrackFocus.Domain.Entities.User", b =>
                {
                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
